### PR TITLE
Update neuron.md

### PR DESCRIPTION
**Pull request by Danie0918**
Updated some screenshots to fit the new UI

### CODE REVIEW

**Comment by jordanmack** [comment]
At the top of [the page](https://nervos-ckb-docs-git-fork-danie0918-patch-1-cryptape.vercel.app/docs/basics/guides/crypto%20wallets/neuron) I see the text `--- id: neuron` and `title: Neuron Wallet`. I believe that is the special meta content at the top of the page and it isn't supposed to display. Your first image should appear below that in the code.

**Comment by Danie0918** [comment]
> At the top of [the page](https://nervos-ckb-docs-git-fork-danie0918-patch-1-cryptape.vercel.app/docs/basics/guides/crypto%20wallets/neuron) I see the text `--- id: neuron` and `title: Neuron Wallet`. I believe that is the special meta content at the top of the code and it isn't supposed to display. Your first image should appear below that in the code. @Danie0918

Ok, this is currently in draft form and will be updated later this week after another feature is developed.

**Comment by Keith-CY** [comment]
Neuron@v0.110.3 has been released at https://github.com/nervosnetwork/neuron/releases/tag/v0.110.3, please make this PR ready for review

**Comment by Keith-CY** [comment]
@jordanmack please have a review

**Comment by jordanmack** [comment]
There are a few minor changes needed.

1. Images should link to the local asset, not a GitHub resource.
2. Images should have a meaningful label since this becomes the alt tag used in the HTML and can affect accessibility.

Example:

```
![Create_wallet](https://github.com/nervosnetwork/docs.nervos.org/assets/122437870/bee6226e-4b03-4adb-b55e-756678de1f42)
```

would be something like

```
![Wallet Seed Phrase](/img/wallet/neuron_01.png)
```

The new image files may also need to be moved to the proper location. The [Docusaurus docs](https://docusaurus.io/docs/static-assets) indicate images should be placed under the static folder, `docs.nervos.org/website/static`. Please feel free to rearrange and delete outdated images from the static folder as needed.

**Comment by Danie0918** [comment]
> There are a few minor changes needed.
> 
> 1. Images should link to the local asset, not a GitHub resource.
> 2. Images should have a meaningful label since this becomes the alt tag used in the HTML and can affect accessibility.
> 
> Example:
> 
> ```
> Create_wallet
> ```
> 
> would be something like
> 
> ```
> Wallet Seed Phrase
> ```
> 
> The new image files may also need to be moved to the proper location. The [Docusaurus docs](https://docusaurus.io/docs/static-assets) indicate images should be placed under the static folder, `docs.nervos.org/website/static`. Please feel free to rearrange and delete outdated images from the static folder as needed.

Updated, please have a review.

**Review by jordanmack — APPROVED** [review]

**Pull request merged**
